// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CxFsDemo")>]
[<assembly: AssemblyProductAttribute("CxFsDemo")>]
[<assembly: AssemblyDescriptionAttribute("Cx F# Demo")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CxFsDemo"
    let [<Literal>] AssemblyProduct = "CxFsDemo"
    let [<Literal>] AssemblyDescription = "Cx F# Demo"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
